# Generated by Django 5.0.4 on 2024-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release",
            field=models.DateField(),
        ),
    ]
