# Generated by Django 5.0.4 on 2024-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0003_movierating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="movierating",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
